# Generated by Django 5.1.1 on 2024-09-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_dob',
            field=models.DateField(default='1999-05-19'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_doctor',
            field=models.CharField(default='Dr. Adam Smith', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_last_appointment',
            field=models.DateTimeField(default='2024-02-19'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_next_appointment',
            field=models.DateTimeField(default='2024-03-19'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_summary',
            field=models.TextField(default='Hypertension'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_treatment_plan',
            field=models.TextField(default='Aspirin'),
        ),
    ]
