# Generated by Django 5.1.1 on 2024-09-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0002_patient_patient_dob_patient_patient_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_summary',
            field=models.TextField(default='No summary yet'),
        ),
    ]
